# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-12-04 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=12, verbose_name='用户名')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('tel', models.CharField(max_length=11, verbose_name='电话')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
    ]
