# Generated by Django 3.1.4 on 2020-12-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.CharField(default=123, max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='tel',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterModelTable(
            name='test',
            table='user_data',
        ),
    ]
