# Generated by Django 3.1.4 on 2020-12-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201225_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='password',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
