# Generated by Django 3.1.4 on 2020-12-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201225_0746'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='user_data',
        ),
    ]
