# Generated by Django 3.1.4 on 2020-12-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201225_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='tel',
        ),
    ]
