# Generated by Django 3.1.4 on 2020-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201225_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('address', models.CharField(default='', max_length=20)),
                ('discription', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'user_post',
            },
        ),
    ]
