# Generated by Django 3.1.4 on 2020-12-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
