# Generated by Django 3.1.4 on 2020-12-26 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 26, 4, 30, 49, 296395), max_length=20),
        ),
    ]
